### ISSUE TITLE
With parrot-7.0 we can remove qrpa

### ISSUE THREAD

**Issue by rurban** [perl6/nqp#209]
See for the failures with parrot-6.11.0: https://gist.github.com/lizmat/dd0f88e6042e7c4ce011
and `t/01-sanity/08-var-array.t` with 
```
Can not get attribute '$!storage' declared in class 'Parcel' with this object
  in block  at gen/parrot/CORE.setting:8248
  in method reify at gen/parrot/CORE.setting:8214
  in method gimme at gen/parrot/CORE.setting:8713
  in method eager at gen/parrot/CORE.setting:8691
  in sub circumfix:<[ ]> at gen/parrot/CORE.setting:9756
  in block <unit> at t/01-sanity/08-var-array.t:26
```

qrpa is not needed anymore. 6model will most likely need an update

best to debug with a debugging parrot. 
e.g. `install/bin/parrot -t20 -- perl6.pbc t/01-sanity/08-var-array.t`

work in the nqp and rakudo branches `parrot-rpa`
See https://github.com/rurban/rakudo/commits/parrot-rpa and https://github.com/perl6/nqp/commits/parrot-rpa

**Comment by rurban** [comment]
Minimized testcase, looping in Exceptions endlessly

```
use v6;
say '1..1';
my @a = (1, 2, 3);

3 == ['a', <2 three>].elems and say 'ok 1';
```

**Comment by rurban** [comment]
The perl6 testsuite found indeed a problem in parrot resizablepmcarray, for which we had no testcase yet. This is now fixed in parrot 7.0
Within this ticket we can now remove the qrpa pmc. This is done in the branch `parrot-rpa`

**Comment by pmichaud** [comment]
Is there are strong motivation for removing QRPA and replacing it with RPA?   In my reading of the code, RPA still has a little baggage associated with it (it's derived from FixedPMCArray, it has a few extra methods we really don't want or need, etc.).

As one of the NQP architects, I just don't see any significant advantage to be gained by changing all of the existing QRPA code to use RPA instead, beyond "it's not needed anymore".  Because QRPA is so fundamental to so much of what we do, I think I prefer being able to tweak and adjust it in NQP directly without having to get changes approved in Parrot.

**Comment by rurban** [comment]
The motivation to remove the outdated qrpa is described in https://github.com/parrot/parrot/issues/1152.
The rewritten rpa is basically an improved qrpa, covering more optimization paths.
Not inheriting from FixedPMCArray of course because we cannot use those methods anymore. Different layout.

You can can of course keep your qrpa also, but see the arguments why the new one is better, and nqp will not need to check for two PMC types, just one.
See the 2 parrot-rpa branches with the suggested changes for nqp and rakudo.

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
