### ISSUE TITLE
Where is the public key to check the pgp signature of nqp tarballs ?

### ISSUE THREAD

**Issue by dod38fr** [perl6/nqp#426]
Hello

Debian strongly suggests to verify the signature of upstream tarballs. Each [release](http://rakudo.org/downloads/nqp/?asset=nqp) of nqp is signed, which is good.

Unfortunately, I [cannot find the pgp public key](https://pgp.mit.edu/pks/lookup?search=0xE1A575CCC2D58C7AA5609FE14710D9D434A4A3C6&op=index) of this signature.

Could you tell me where I can find this pubilc key ? (it may be simpler for you to upload your public key to a pgp key server)

All the best

**Comment by AlexDaniel** [comment]
OK, so my key can be found here: https://keybase.io/alexdaniel (it links to multiple sources so that you can cross-verify).
Same key is also on my github account: https://api.github.com/users/AlexDaniel/gpg_keys

In case that's not enough I also submitted the key to [pgp.mit.edu](https://pgp.mit.edu/pks/lookup?search=0xE1A575CCC2D58C7AA5609FE14710D9D434A4A3C6&op=index) server that you mentioned.

Please close if that's enough, or let me know what can be done better.

**Comment by dod38fr** [comment]
I've retrieved the key from pgp.mit.edu, that's the most simple for me.

Download and gpg verification now works fine. :-)

Thanks for the help
