### ISSUE TITLE
[jvm] non-throw ExceptionHandling#dieInternal

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#506]
I see there are many calls to `ExceptionHandling#dieInternal` which get the Exception but not throw, it looks weird, if we don't throw it, we leave these exceptions in sink context. Why? @jnthn @usev6

**Comment by pmurias** [comment]
It's most likely a bug

**Comment by pmurias** [comment]
I investigated it some more and it seems like that the exception returned from ExceptionHandling.dieInternal never get thrown but is exists because the compiler doesn't known that ExceptionHandling.dieInternal never returns.

Stuff I found in the irc logs
jnthn: sorear: dieInternal returns an exception so we can write "throw ExceptionHandling.dieInternal(...)" and Java compiler is happily convinced we're not coming back.

**Comment by TisonKun** [comment]
@pmurias does it mean that we modify some global state at `dieInternal` but whether throw the (returned) Exception is depend?

**Comment by pmurias** [comment]
dieInternal throws an exception, so it never actually returns anything.

`int foo() {
    throw ExceptionHandling.dieInternal();
    // the compiler knows we never get here
}

int foo() {
   ExceptionHandling.dieInternal(); //always throws exception, but the compiler doesn't know
   // we never get here but the compiler doesn't know so it complains
}`

**Comment by TisonKun** [comment]
@pmurias thanks for the clarification!
