### ISSUE TITLE
Why some method take ThreadContext as parameter but never use it

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#508]
It looks like a common case. Is the ThreadContext a placeholder that keeps convenience resolve methods?

**Comment by jnthn** [comment]
It's typically needed in a lot of places, and it makes for a more consistent API if it's consistently past. The exception is for stuff in `Ops`, when we can maybe save quite a bit on code-gen size due to there being lots of calls, or greatly simplify code-gen by taking it as a final argument rather than a first one.

**Comment by TisonKun** [comment]
thanks for the explanation!
