### ISSUE TITLE
isprime_I rounds parameter is broken?

### ISSUE THREAD

**Issue by ajs** [perl6/nqp#560]
I know that calling isprime_I from Perl6 isn't exactly best practices, but for strange reasons, I really wanted to use the otherwise unexposed second parameter which pameterizes the number of R-M rounds to perform in the test.

However, I seem to have run into some kind of bug:

```Shell
$ perl6 -M nqp -e 'say nqp::hllbool(nqp::isprime_I(3,256))'
True
$ perl6 -M nqp -e 'say nqp::hllbool(nqp::isprime_I(3,257))'
False
```

Am I using this wrong, or is this actually an nqp (or perhaps Moar?) bug?

I have a very vague memory that I've run into this years ago, but I can't immediately find any evidence of that via searching...

**Comment by timo** [comment]
Hi @ajs, libtommath returns an error value if the number of rounds is above 256, but moar never checked if the return value is not equal to MP_OKAY; since rakudo only ever passes 100 there, we never ran into this issue. We'll have a patch up later that checks the return value and throw an exception if MP_VAL or similar is returned from libtom, that would give a much more sensible result for people using nqp::isprime_I manually.

**Comment by ajs** [comment]
Well nuts! I guess I'm going to have to break down and implement my own is-prime that can do large numbers of rounds. It's absurd, of course, since any operation on numbers requiring such large numbers of rounds are surely going to take longer than you have, but I want the assurances to scale.

FWIW: background on what I'm doing: I want Math::Sequences::Integer to provide a tuning parameter for the largest integer you are likely to care about in the list of primes. That way, the number of rounds can be tuned to that size. Now I just need a good formula for number of rounds to probability of a false negative.

Thanks for the feedback @timo !

**Comment by MasterDuke17** [comment]
@ajs MoarVM doesn't use it, but libtommath does provide an `mp_prime_miller_rabin_trials` function (https://github.com/libtom/libtommath/blob/develop/tommath.h#L603-L606) that tells you how many rounds you need for a certain size input.
